.\" generated with Ron/v0.3
.\" http://github.com/rtomayko/ron/
.
.TH "SURSERVER" "1" "January 2010" "" ""
.
.SH "NAME"
\fBsurserver\fR \-\- subtle user repository
.
.SH "SYNOPSIS"
\fBsurserver\fR
.
.SH "DESCIPTION"
\fBsurserver\fR is the server part of \fBsur\fR, it maintains a repository and
allows access to it via http on default port 4567.
.
.SH "EXAMPLES"
.
.nf

surserver 
.
.fi
.
.SH "BUGS"
Report bugs to unexist@dorfelite.net
.
.br
Homepage: http://sur.subtle.de
.
.br
.
.SH "COPYRIGHT"
Copyright (c) Christoph Kappel \fIunexist@dorfelite.net\fR
.
.SH "SEE ALSO"
sur(1), subtle(1), subtler(1), subtlext(1)
