#
#	@package subtle - window manager
#
# @file SConscript file
#	@copyright Copyright (c) 2005-2008 Christoph Kappel <unexist@dorfelite.net>
#	@version $Id$
#
# This program can be distributed under the terms of the GNU GPL.
# See the file COPYING.
#

Import("env")

sublets = Split("""
	battery.lua
	clock.lua
	loadavg.lua
	notify.lua
""")

env.Alias("install", env.Install(env.subst("$datadir" + "/subtle"), sublets))
