#
#	subtle - window manager
#	Copyright (c) 2005-2008 Christoph Kappel
#
#	See the COPYING file for the license in the latest tarball.
#
#	$Id$
#

Import("env")

sublets = Split("""
	battery.lua
	clock.lua
	loadavg.lua
	notify.lua
""")

env.Alias("install", env.Install(env.subst("$datadir" + "/subtle"), sublets))
