#
#	subtle - window manager
#	Copyright (c) 2005-2008 Christoph Kappel
#
#	See the COPYING file for the license in the latest tarball.
#
#	$Id$
#

Import("env")

env.Alias("install", env.Install(env.subst("$sysconfdir" + "/subtle"), "config.lua"))
