
	##
	#	subtle - window manager
	#	Copyright (c) 2005-2007 Christoph Kappel
	#
	#	See the COPYING file for the license in the latest tarball.
	#
	#	$Header$
	##

Import("env")

source = Split("""
	client.c
	display.c
	event.c
	ewmh.c
	key.c
	lua.c
	main.c
	sublet.c
	tile.c
	util.c
	view.c
	win.c
""")

subtle = env.Program('subtle', source)
subtler = env.Program('subtler', 'subtler.c')

env.Alias("install", env.Install(env.subst("$bindir"), subtle))
env.Alias("install", env.Install(env.subst("$bindir"), subtler))
