# Environment
Import('env')

source = Split("""
	client.c
	display.c
	event.c
	ewmh.c
	key.c
	lua.c
	main.c
	sublet.c
	tile.c
	util.c
	view.c
	win.c
""")

subtle = env.Program('subtle', source)
subtler = env.Program('subtler', 'subtler.c')
